# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgotpassword_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.email_passreset_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.email_passreset_lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_passreset_lineEdit.setFont(font)
        self.email_passreset_lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgbargb(255, 255, 255, 210);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;")
        self.email_passreset_lineEdit.setObjectName("email_passreset_lineEdit")
        self.verticalLayout_3.addWidget(self.email_passreset_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.new_password_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.new_password_lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.new_password_lineEdit.setFont(font)
        self.new_password_lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgbargb(255, 255, 255, 210);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;")
        self.new_password_lineEdit.setObjectName("new_password_lineEdit")
        self.verticalLayout_3.addWidget(self.new_password_lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.confirm_new_lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.confirm_new_lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.confirm_new_lineEdit_2.setFont(font)
        self.confirm_new_lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgbargb(255, 255, 255, 210);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom: 7px;")
        self.confirm_new_lineEdit_2.setObjectName("confirm_new_lineEdit_2")
        self.verticalLayout_3.addWidget(self.confirm_new_lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.confirm_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.confirm_pushButton.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.confirm_pushButton.setFont(font)
        self.confirm_pushButton.setStyleSheet("QPushButton#confirm_pushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#confirm_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(139, 139, 139));\n"
"}\n"
"\n"
"QPushButton#confirm_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(139, 139, 139);\n"
"}")
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.verticalLayout_4.addWidget(self.confirm_pushButton)
        self.goToGenerate_pushButton = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.goToGenerate_pushButton.setFont(font)
        self.goToGenerate_pushButton.setStyleSheet("QPushButton#goback_pushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#goback_pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(139, 139, 139));\n"
"}\n"
"\n"
"QPushButton#goback_pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color: rgba(139, 139, 139);\n"
"}")
        self.goToGenerate_pushButton.setObjectName("goToGenerate_pushButton")
        self.verticalLayout_4.addWidget(self.goToGenerate_pushButton)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Password Reset"))
        self.email_passreset_lineEdit.setPlaceholderText(_translate("Form", "Enter OTP"))
        self.new_password_lineEdit.setPlaceholderText(_translate("Form", "Enter New Password"))
        self.confirm_new_lineEdit_2.setPlaceholderText(_translate("Form", "Re-Enter New Password"))
        self.confirm_pushButton.setText(_translate("Form", "Confirm"))
        self.goToGenerate_pushButton.setText(_translate("Form", "Go Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
